### ISSUE TITLE
CRA example

### ISSUE THREAD

**Issue by mmarkelov** [playwright-community/playwright-jest-examples#2]
What do you think about creating an example with usage of **create-react-app**? I can make PR)

**Comment by mxschmitt** [comment]
> What do you think about creating an example with usage of **create-react-app**? I can make PR)

sounds good!

**Comment by mmarkelov** [comment]
@mxschmitt I've got configured this [repo](https://github.com/mmarkelov/jest-playwright-examples) but for now IDK how can I add this to your example. What do you think?

**Comment by mxschmitt** [comment]
Looks awesome, I would maybe remove the service worker stuff. otherwise its super!

**Comment by mmarkelov** [comment]
@mxschmitt I think we can close it
